Controllers/AnagraficaController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Prova1_M_5.Models;
using Prova1_M_5.Service;

namespace Prova1_M_5.Controllers
{
    public class AnagraficaController : Controller
    {

        private readonly ILogger<AnagraficaController> _logger;
        private readonly IAnagraficaService _anagraficaService;

        public AnagraficaController(ILogger<AnagraficaController> logger, IAnagraficaService anagraficaService)
        {
            _logger = logger;
            _anagraficaService = anagraficaService;
        }

        // GET: test
        public ActionResult Index()
        {
            var anagrafiche = _anagraficaService.GetAll();

            return View(anagrafiche);
           
        }


        public IActionResult Create()
        {
            return View();
        }

        // POST: Home/Create
        [HttpPost]

        public IActionResult Create(Anagrafica anagrafica)
        {
            _anagraficaService.Add(anagrafica);
            return RedirectToAction(nameof(Index));
        }


      
     
      
    }
}

Controllers/TipoViolazioneController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Prova1_M_5.Models;
using Prova1_M_5.Service;

namespace Prova1_M_5.Controllers
{
    public class TipoViolazioneController : Controller
    {

        private readonly ILogger<TipoViolazioneController> _logger;
        private readonly ITipoViolazioneService _TipoViolazione;

        public TipoViolazioneController(ILogger<TipoViolazioneController> logger, ITipoViolazioneService tipoViolazioneService)
        {
            _logger = logger;
            _TipoViolazione = tipoViolazioneService;
        }


      
        public IActionResult Index()
        {
            var Viol = _TipoViolazione.GetAll();


            return View(Viol);
        }

       
        
        public IActionResult Create()
        {
            return View();

        }

        [HttpPost]
        public IActionResult Create(TipoViolazione tipoViolazione)
        {
        _TipoViolazione.Add(tipoViolazione);
            return RedirectToAction(nameof(Index));
        
        }

      
    }
}

Controllers/VerbaleController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Prova1_M_5.Models;
using Prova1_M_5.Service;

namespace Prova1_M_5.Controllers
{
    public class VerbaleController : Controller
    {
        private readonly ILogger<VerbaleController> _logger;
        
       private readonly IVerbaleService _verbaleService;
        private readonly IAnagraficaService _anagraficaService;
        private readonly ITipoViolazioneService _violazioneService; 
        public VerbaleController(ILogger<VerbaleController> logger, IVerbaleService verbaleService, IAnagraficaService anagraficaService, ITipoViolazioneService tipoviolazioneService )
        {
            _logger = logger;
            _verbaleService = verbaleService;
       _anagraficaService = anagraficaService;  
            _violazioneService = tipoviolazioneService;

        }

        public IActionResult Index()
        {
            var verb = _verbaleService.GetAll();

            return View(verb);

        }



        public IActionResult Create()
        {
            ViewBag.Anagrafiche = _anagraficaService.GetAll();
            ViewBag.TipiViolazione = _violazioneService.GetAll();
            return View(new Verbale());
        }

       
        [HttpPost]
       
        public IActionResult Create(Verbale verbale)
        {
           
           
             _verbaleService.Add(verbale);
               
            
          
             return RedirectToAction(nameof(Index));
        }



    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Prova1_M_5</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Prova1_M_5.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Polizia_di_Stato_-_Reparto_mobile.jpg/800px-Polizia_di_Stato_-_Reparto_mobile.jpg" alt="Logo" style="height: 40px;" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Anagrafica" asp-action="Index">Anagrafica</a>
                        </li>
                           <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Verbale" asp-action="Index">Verbali</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TipoViolazione" asp-action="Index">Violazioni</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Prova1_M_5 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>