Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Prova1_M_5.Models;
using Prova1_M_5.Service;
using System.Diagnostics;

namespace Prova1_M_5.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        

       

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
           
        }

        public  IActionResult Index()
        {


            return View();

        }

        public IActionResult Privacy()
        {
            return View();
        }

        // /////////////////////////////////////////////////////

        public IActionResult Create()
        {
            return View();
        }

      
        
       
      









        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/QueryController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Prova1_M_5.Service;

namespace Prova1_M_5.Controllers
{
    public class QueryController : Controller
    {
        private readonly ILogger<QueryController> _logger;
        private readonly IVerbaleService _verbaleService;

        public QueryController(ILogger<QueryController> logger, IVerbaleService verbaleService)
        {
            _logger = logger;
            _verbaleService = verbaleService;
        }





        public IActionResult TotaleVerbaliPerTrasgressore()
        {
            var result = _verbaleService.GetVerbaliPerTrasgressore();
            return View(result);
        }

        public IActionResult TotalePuntiDecurtatiPerTrasgressore()
        {
            var result = _verbaleService.GetPuntiDecurtatiPerTrasgressore();
            return View(result);
        }


        public IActionResult ViolazioniSuperano10Punti()
        {
            var result = _verbaleService.GetViolazioniSuperano10Punti();
            return View(result);
        }

        public IActionResult ViolazioniImportoMaggiore400()
        {
            var result = _verbaleService.GetViolazioniImportoMaggiore400();
            return View(result);
        }






    }
}

Views/Home/Create.cshtml
@model Prova1_M_5.Models.Anagrafica

@{
    ViewData["Title"] = "Create Anagrafica";
}

<h1>Create Anagrafica</h1>

<h4>Anagrafica</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div class="form-group">
                <label asp-for="Cognome" class="control-label"></label>
                <input asp-for="Cognome" class="form-control" />
                <span asp-validation-for="Cognome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Indirizzo" class="control-label"></label>
                <input asp-for="Indirizzo" class="form-control" />
                <span asp-validation-for="Indirizzo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Città" class="control-label"></label>
                <input asp-for="Città" class="form-control" />
                <span asp-validation-for="Città" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CAP" class="control-label"></label>
                <input asp-for="CAP" class="form-control" />
                <span asp-validation-for="CAP" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cod_Fisc" class="control-label"></label>
                <input asp-for="Cod_Fisc" class="form-control" />
                <span asp-validation-for="Cod_Fisc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Home/Index.cshtml
@model IEnumerable<Anagrafica>

@{
    ViewData["Title"] = "Home Page";
}

<h1 class="text-center text-light"> Benvenuto Agente </h1>
<p class="text-center">Il dipartimento si scusa per l'app ma i fondi sono finiti</p>


<div class="list-group ">

    <a class="list-group-item list-group-item-action text-center" asp-area="" asp-controller="Query" asp-action="TotaleVerbaliPerTrasgressore">Totale Verbali per Trasgressore</a>
    <a class="list-group-item list-group-item-action text-center" asp-area="" asp-controller="Query" asp-action="TotalePuntiDecurtatiPerTrasgressore">Totale Punti Decurtati per Trasgressore</a>
    <a class="list-group-item list-group-item-action text-center" asp-area="" asp-controller="Query" asp-action="ViolazioniImportoMaggiore400">Violazioni con Importo Maggiore di 400 Euro</a>
    <a class="list-group-item list-group-item-action text-center" asp-area="" asp-controller="Query" asp-action="ViolazioniSuperano10Punti">Violazioni che Superano 10 Punti</a>
</div>            